name: ridenow_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  custom_info_window: ^1.0.1
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.0
  freezed_annotation: ^2.4.4  
  geolocator: ^14.0.0
  get_it: ^8.0.3
  google_maps_flutter: ^2.12.1
  injectable: ^2.5.0
  page_transition: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7  
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/